name: mvc_framework
description: A starting point for Dart libraries or applications.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.2.1

# Add regular dependencies here.
dependencies:
  shelf: ^1.4.1
  shelf_static: ^1.1.2
  # path: ^1.8.0

dev_dependencies:
  lint: ^2.3.0
  lints: ^2.1.0
  test: ^1.24.0
